spring:  
  profiles:  
    active: dev 
---  
spring: 
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myboot?useUnicode=true&characterEncoding=utf-8
    max-active: 300
    max-idle: 10
    min-idle: 8
    password: root
    username: root 
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    validation-query: select 1 
    filters: stat
    max-wait: 60000
    pool-prepared-statements: true
  
server:
  port: 80
logging:
  config: classpath:public/logback.xml
  level:
    tk:
      mybatis: TRACE
mybatis:
  type-aliases-package: com.crab.mybatis.domain
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:public/mybatis-config.xml
mapper:
  mappers:
    - com.qfpie.server.util.QkMapper
  not-empty: false
  identity: oracle


---  
spring:  
  profiles: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ""
    max-active: 300
    max-idle: 10
    min-idle: 8
    password: "" 
    username: "" 
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    validation-query: select 1 
    filters: stat
    max-wait: 60000
    pool-prepared-statements: true  
server:
  port: 9
logging:
  level:
    tk:
      mybatis: TRACE



 