package com.crab.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mybatis.generator.paginator.Page;
import org.mybatis.generator.paginator2.PageRowBounds;
import org.mybatis.generator.paginator3.PageBounds;

import com.crab.mybatis.domain.MyUser;

@Mapper
public interface MyUserMapper {

	/**
	 * findOne
	 * 
	 * @param id
	 * @return
	 */
	@Select(value = "select * from my_user where id=#{0}")
	MyUser findOne(int id);

	/**
	 * findAll
	 * 
	 * @return
	 */
	@Select(value = "select * from my_user")
	List<MyUser> findAll();

	/**
	 * findAll
	 * 
	 * @return
	 */
	@Select(value = "select * from my_user")
	List<MyUser> findAllPage(Page page);
	
	@Select(value = "select * from my_user")
	List<MyUser> findAllPage2(PageBounds page);
	
	@Select(value = "select * from my_user")
	List<MyUser> findAllPage3(PageRowBounds page);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table my_user
	 *
	 * @mbg.generated
	 */
	MyUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table my_user
	 *
	 * @mbg.generated
	 */
	int deleteLogicByIds(@Param("deleteFlag") int deleteFlag, @Param("ids") Integer[] ids);
}