package com.crab.mybatis.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.crab.mybatis.domain.SysUser;

@Mapper
public interface SysUserMapper {

	@Select(value = "select * from sys_user where user=#{0} and pwd=#{1}")
	SysUser getUserByPwd(String user, String pwd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated
	 */
	SysUser selectByPrimaryKey(Integer id);
}