spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootshiro
    max-active: 300
    max-idle: 10
    min-idle: 8
    password: root
    username: root 
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    validation-query: select 1 
    filters: stat
    max-wait: 60000
    pool-prepared-statements: true

server:
  port: 80
logging:
  config: classpath:public/logback.xml
  level:
    tk:
      mybatis: TRACE
mybatis:
  type-aliases-package: com.crab.shiro.domain
  mapper-locations: classpath:mapper/**/*.xml
mapper:
  mappers:
    - com.qfpie.server.util.QkMapper
  not-empty: false
  identity: oracle


---
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ""
    max-active: 300
    max-idle: 10
    min-idle: 8
    password: ""
    username: ""
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    validation-query: select 1
    filters: stat
    max-wait: 60000
    pool-prepared-statements: true
server:
  port: 9090
logging:
  level:
    tk:
      mybatis: TRACE
mybatis:
  type-aliases-package: com.qfpie.server.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers:
    - com.qfpie.server.util.QkMapper
  not-empty: false
  identity: MYSQL


 