server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    #password:
    timeout: 1000
    database: 0  #默认有16个db(集群模式下无多db概念，取而代之是hash槽)，默认是第0个
    lettuce:
      pool:
        max-active: 8 #最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 #最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  #最大空闲连接 默认 8
        min-idle: 0
    cluster:
      nodes:
       - 172.19.165.222:9001
       - 172.19.165.222:9002
       - 172.19.165.222:9003
       - 172.19.165.222:9004
       - 172.19.165.222:9005
       - 172.19.165.222:9006