package com.crab.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.crab.mybatis.domain.SysDataDic;

@Mapper
public interface SysDataDicMapper {
	/**
	 * 根据用户查询密码
	 * @param userName
	 * @param pwd
	 * @return
	 */
	@Select(value = "select * from sys_data_dic where code=#{0}")
	List<SysDataDic> findByCode(Integer code);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    SysDataDic selectByPrimaryKey(Integer id);

}