package com.crab.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class MyUser implements Serializable {
    /**
     *
     *  主键, 所属表字段为my_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     *  用户名, 所属表字段为my_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     *  性别, 所属表字段为my_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     *  年龄, 所属表字段为my_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     *  地址, 所属表字段为my_user.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     *  电话, 所属表字段为my_user.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     *  是否成人, 所属表字段为my_user.is_adult
     *
     * @mbg.generated
     */
    private String is_adult;

    /**
     *
     *  兴趣, 所属表字段为my_user.intrest
     *
     * @mbg.generated
     */
    private String intrest;

    /**
     *
     *  生日, 所属表字段为my_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     *  体重, 所属表字段为my_user.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     *
     *  创建时间, 所属表字段为my_user.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.id
     *
     * @return the value of my_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.id
     *
     * @param id the value for my_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.name
     *
     * @return the value of my_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.name
     *
     * @param name the value for my_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.sex
     *
     * @return the value of my_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.sex
     *
     * @param sex the value for my_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.age
     *
     * @return the value of my_user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.age
     *
     * @param age the value for my_user.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.addr
     *
     * @return the value of my_user.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.addr
     *
     * @param addr the value for my_user.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.tel
     *
     * @return the value of my_user.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.tel
     *
     * @param tel the value for my_user.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.is_adult
     *
     * @return the value of my_user.is_adult
     *
     * @mbg.generated
     */
    public String getIs_adult() {
        return is_adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.is_adult
     *
     * @param is_adult the value for my_user.is_adult
     *
     * @mbg.generated
     */
    public void setIs_adult(String is_adult) {
        this.is_adult = is_adult == null ? null : is_adult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.intrest
     *
     * @return the value of my_user.intrest
     *
     * @mbg.generated
     */
    public String getIntrest() {
        return intrest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.intrest
     *
     * @param intrest the value for my_user.intrest
     *
     * @mbg.generated
     */
    public void setIntrest(String intrest) {
        this.intrest = intrest == null ? null : intrest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.birthday
     *
     * @return the value of my_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.birthday
     *
     * @param birthday the value for my_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.weight
     *
     * @return the value of my_user.weight
     *
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.weight
     *
     * @param weight the value for my_user.weight
     *
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.create_time
     *
     * @return the value of my_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.create_time
     *
     * @param create_time the value for my_user.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MyUser other = (MyUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getAddr() == null ? other.getAddr() == null : this.getAddr().equals(other.getAddr()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getIs_adult() == null ? other.getIs_adult() == null : this.getIs_adult().equals(other.getIs_adult()))
            && (this.getIntrest() == null ? other.getIntrest() == null : this.getIntrest().equals(other.getIntrest()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getCreate_time() == null ? other.getCreate_time() == null : this.getCreate_time().equals(other.getCreate_time()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getAddr() == null) ? 0 : getAddr().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getIs_adult() == null) ? 0 : getIs_adult().hashCode());
        result = prime * result + ((getIntrest() == null) ? 0 : getIntrest().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getCreate_time() == null) ? 0 : getCreate_time().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", addr=").append(addr);
        sb.append(", tel=").append(tel);
        sb.append(", is_adult=").append(is_adult);
        sb.append(", intrest=").append(intrest);
        sb.append(", birthday=").append(birthday);
        sb.append(", weight=").append(weight);
        sb.append(", create_time=").append(create_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}