package com.crab.mybatis.domain;

import java.io.Serializable;

public class SysDataDic implements Serializable {
    /**
     *
     *  主键, 所属表字段为sys_data_dic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     *  父主键, 所属表字段为sys_data_dic.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     *  页面通过它取值, 所属表字段为sys_data_dic.code
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     *
     *  键, 所属表字段为sys_data_dic.dic_key
     *
     * @mbg.generated
     */
    private String dic_key;

    /**
     *
     *  值, 所属表字段为sys_data_dic.dic_value
     *
     * @mbg.generated
     */
    private String dic_value;

    /**
     *
     *  是否停用(-1-停用, 空或0-启用), 所属表字段为sys_data_dic.is_stop
     *
     * @mbg.generated
     */
    private Integer is_stop;

    /**
     *
     *  注释, 所属表字段为sys_data_dic.comet
     *
     * @mbg.generated
     */
    private String comet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    private int custom = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.id
     *
     * @return the value of sys_data_dic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.id
     *
     * @param id the value for sys_data_dic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.pid
     *
     * @return the value of sys_data_dic.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.pid
     *
     * @param pid the value for sys_data_dic.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.code
     *
     * @return the value of sys_data_dic.code
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.code
     *
     * @param code the value for sys_data_dic.code
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.dic_key
     *
     * @return the value of sys_data_dic.dic_key
     *
     * @mbg.generated
     */
    public String getDic_key() {
        return dic_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.dic_key
     *
     * @param dic_key the value for sys_data_dic.dic_key
     *
     * @mbg.generated
     */
    public void setDic_key(String dic_key) {
        this.dic_key = dic_key == null ? null : dic_key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.dic_value
     *
     * @return the value of sys_data_dic.dic_value
     *
     * @mbg.generated
     */
    public String getDic_value() {
        return dic_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.dic_value
     *
     * @param dic_value the value for sys_data_dic.dic_value
     *
     * @mbg.generated
     */
    public void setDic_value(String dic_value) {
        this.dic_value = dic_value == null ? null : dic_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.is_stop
     *
     * @return the value of sys_data_dic.is_stop
     *
     * @mbg.generated
     */
    public Integer getIs_stop() {
        return is_stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.is_stop
     *
     * @param is_stop the value for sys_data_dic.is_stop
     *
     * @mbg.generated
     */
    public void setIs_stop(Integer is_stop) {
        this.is_stop = is_stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_data_dic.comet
     *
     * @return the value of sys_data_dic.comet
     *
     * @mbg.generated
     */
    public String getComet() {
        return comet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_data_dic.comet
     *
     * @param comet the value for sys_data_dic.comet
     *
     * @mbg.generated
     */
    public void setComet(String comet) {
        this.comet = comet == null ? null : comet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysDataDic other = (SysDataDic) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getDic_key() == null ? other.getDic_key() == null : this.getDic_key().equals(other.getDic_key()))
            && (this.getDic_value() == null ? other.getDic_value() == null : this.getDic_value().equals(other.getDic_value()))
            && (this.getIs_stop() == null ? other.getIs_stop() == null : this.getIs_stop().equals(other.getIs_stop()))
            && (this.getComet() == null ? other.getComet() == null : this.getComet().equals(other.getComet()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getDic_key() == null) ? 0 : getDic_key().hashCode());
        result = prime * result + ((getDic_value() == null) ? 0 : getDic_value().hashCode());
        result = prime * result + ((getIs_stop() == null) ? 0 : getIs_stop().hashCode());
        result = prime * result + ((getComet() == null) ? 0 : getComet().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", code=").append(code);
        sb.append(", dic_key=").append(dic_key);
        sb.append(", dic_value=").append(dic_value);
        sb.append(", is_stop=").append(is_stop);
        sb.append(", comet=").append(comet);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    public void setCustom(int custom) {
        this.custom=custom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_dic
     *
     * @mbg.generated
     */
    public int getCustom() {
        return custom;
    }
}