spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iti?useUnicode=true&characterEncoding=utf-8
    max-active: 300
    max-idle: 10
    min-idle: 8
    username: root
    password: root
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    validation-query: select 1 
    filters: stat
    max-wait: 60000
    pool-prepared-statements: true
#  resources:
#    static-locations: classpath:/static/
##Note:Don't config static by static-locations, otherwise, swagger-ui cannot work, Boot configured default.

server:
  port: 8080
  #keytool -genkey -alias jyax  -storetype PKCS12 -keyalg RSA -keysize 2048  -keystore keystore.p12 -validity 3650
  #ssl:
  #  key-store: classpath:public/keystore.p12
  #  key-store-password: 123456,
  #  keyStoreType: PKCS12
  #  keyAlias: jyax
  #for dev only.
logging:
  config: classpath:public/log4j2.xml
  level:
    tk:
      mybatis: TRACE
mybatis:
  type-aliases-package: com.crab.domain
  mapper-locations: classpath:com/crab/mapper/**/*.xml
  config-location: classpath:public/mybatis-config.xml

